[package]
name = "minecalc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii_table = "4.0.2"
eframe = "0.21.3"
rfd = "0.11.2"
tracing-subscriber = "0.3.16"
